#Setting the amount the world border will increase in radius every unique player join.
AmountToGrow:
  #Size in blocks.
  size: 250
  #multiplier of size ^^
  multiplier: 1
  #Speed in seconds.
  speed: 0