name: WorldBoarderFirstJoin
version: '1.2'
main: com.chownnick.worldBorderFirstJoin.WorldBorderFirstJoin
folia-supported: 'true'
api-version: '1.21'
authors: [ Ethman_G ]
description: Adds "x" to world border for every unique join.
